In [54]:
import sklearn
import sklearn.datasets

In [55]:
iris = sklearn.datasets.load_iris()

x = iris.data
# 0: setosa, 1: virginica, 2: versicolor
y = iris.target

In [56]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

iris = pd.read_csv(
    "http://archive.ics.uci.edu/ml/" +
    "machine-learning-databases/iris/iris.data",
    header=None)
iris_measures = iris.iloc[:, :4].to_numpy()
iris_species = iris.iloc[:, 4].to_numpy()
iris_species

encoder = LabelEncoder()
encoder.fit(iris_species)
iris_species_one_hot = encoder.transform(iris_species)

scaler = StandardScaler()
scaler.fit(iris_measures)
iris_measures_scaled = scaler.transform(iris_measures)

iris_measures_scaled

x = iris_measures_scaled
y = iris_species_one_hot

In [57]:
# [5, 3, 1.5, 0.2] -> 0

In [58]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y)

In [59]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model.fit(x_train, y_train)

KNeighborsClassifier()

In [60]:
import numpy as np

test_data = np.array([
    [5.3, 3.4, 1.9, 0.6],
    [6.0, 3.0, 4.7, 1.5],
    [6.5, 3.1, 5.0, 1.7]
])

In [61]:
model.predict_proba(test_data)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [67]:
model = DecisionTreeClassifier(max_depth=2)

model.fit(x_train, y_train)

y_prediction = model.predict(x_test)

from sklearn import metrics
metrics.accuracy_score(y_prediction, y_test)

0.8947368421052632

In [66]:
classifiers = [
    DecisionTreeClassifier(),
    DecisionTreeClassifier(max_depth=3),
    SVC(),
    SVC(kernel="linear"),
    GaussianNB()
]

for classifier in classifiers:
    print("training", classifier)
    classifier.fit(x, y)
    print(classifier.predict(test_data))


training DecisionTreeClassifier()
[2 2 2]
training DecisionTreeClassifier(max_depth=3)
[2 2 2]
training SVC()
[0 0 0]
training SVC(kernel='linear')
[1 2 2]
training GaussianNB()
[2 2 2]
