In [1]:
import pandas as pd

titanic = pd.read_csv(
    "https://public.opendatasoft.com/explore/dataset/titanic-passengers/download",
    sep=";",
)

In [30]:
titanic_1 = titanic.drop(columns=["name", "ticket", "cabin", "passengerid", "embarked", "parch", "survived_bool"])
titanic_1["survived"] = titanic_1["survived"].replace({"Yes": True, "No": False})
titanic_1["female"] = titanic_1["sex"].replace({"male": False, "female": True})
titanic_1 = titanic_1.drop(columns=["sex"])
titanic_1

survived  pclass   age  sibsp      fare  female
0        True       1  28.0      0   26.5500   False
1       False       3  36.0      0    7.4958   False
2        True       2   3.0      1   41.5792    True
3        True       2  40.0      0   13.0000    True
4       False       3  32.0      0    7.7500   False
..        ...     ...   ...    ...       ...     ...
886      True       1  21.0      2  262.3750    True
887      True       1  51.0      1   77.9583    True
888     False       3  28.0      0    9.5000   False
889      True       3   5.0      2   19.2583    True
890     False       1  64.0      0   26.0000   False

[891 rows x 6 columns]

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [31]:
titanic_1 = titanic_1.dropna()

In [32]:
y = titanic_1["survived"].to_numpy()
x = titanic_1.loc[:, "pclass":"female"].to_numpy()
x

array([[1, 28.0, 0, 26.55, False],
       [3, 36.0, 0, 7.4958, False],
       [2, 3.0, 1, 41.5792, True],
       ...,
       [3, 28.0, 0, 9.5, False],
       [3, 5.0, 2, 19.2583, True],
       [1, 64.0, 0, 26.0, False]], dtype=object)

In [33]:
model = LinearRegression()

model.fit(x, y)

LinearRegression()

In [34]:
model.predict(x)[:10]

array([0.50890563, 0.06078746, 0.90727721, 0.71613172, 0.08683347,
       0.21746109, 0.40154597, 0.02206357, 0.13229273, 0.03054742])

In [35]:
y[:10]

array([ True, False,  True,  True, False, False, False, False, False,
       False])