# NumPy

In [1]:
import numpy as np

## basics

In [2]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## performance

In [5]:
# performance comparison

import time

input_data = range(0, 1000001)
squares = []

start = time.perf_counter()
for element in input_data:
    squares.append(element * element)
end = time.perf_counter()

print(end - start)


input_data_np = np.array(input_data, dtype="int64")

start = time.perf_counter()
squares_np = input_data_np * input_data_np
end = time.perf_counter()

print(end - start)


0.20988720000000072
0.005451100000000153


In [6]:
a2d.size

9

In [7]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
a2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
a2d.dtype

dtype('int32')

## creating arrays

In [12]:
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.full((2, 6), 1.0)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0, 1.0, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.arange(0, 3.14, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [16]:
rng = np.random.default_rng(seed=1)
print(rng.random((2, 2)))
print(rng.random((2, 2)))
print(rng.random((2, 2)))
print(rng.random((2, 2)))

r = rng.random((2, 2))
print(r)

r[1, 1]

[[0.51182162 0.9504637 ]
 [0.14415961 0.94864945]]
[[0.31183145 0.42332645]
 [0.82770259 0.40919914]]
[[0.54959369 0.02755911]
 [0.75351311 0.53814331]]
[[0.32973172 0.7884287 ]
 [0.30319483 0.45349789]]
[[0.1340417  0.40311299]
 [0.20345524 0.26231334]]


0.2623133404418495

## selecting elements

In [17]:
a1d[0]

0

In [18]:
a2d[0, 1]

2

In [19]:
a2d[0, :]

array([1, 2, 3])

In [20]:
a2d[:, 1]

array([2, 5, 8])

In [21]:
a1d[:3]

array([0, 1, 2])

In [22]:
a1d[3:6]

array([3, 4, 5])

In [23]:
a1d[6:]

array([6, 7, 8, 9])

In [24]:
a1d[0:8:2]

array([0, 2, 4, 6])

## operations on arrays

In [25]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])

In [26]:
a + b

array([2, 3, 4, 5])

In [27]:
a < b

array([ True,  True, False, False])

In [28]:
a == b

array([False, False,  True, False])

In [29]:
if np.array_equal(a, b):
    print("hello")

In [30]:
a + 1

array([1, 2, 3, 4])

In [31]:
a * a

array([0, 1, 4, 9])

In [32]:
# element-wise multiplication
a2d * a2d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [33]:
# matrix multiplication
a2d @ a2d

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [34]:
a2d_ = np.array([[ "a", "b", "c"],
                [16, 25, 36],
                [49, 64, 81]], dtype="object")

In [35]:
headings = a2d_[0, :]
headings

array(['a', 'b', 'c'], dtype=object)

In [36]:
data = a2d_[1:, :]
data

array([[16, 25, 36],
       [49, 64, 81]], dtype=object)

In [37]:
a + np.pi

array([3.14159265, 4.14159265, 5.14159265, 6.14159265])

In [38]:
# nan = not-a-number: unknown / missing data
np.nan

nan

In [39]:
np.nan * 0

nan

In [40]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [41]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [42]:
np.cos(np.pi)

-1.0

In [43]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.sum(a2d)

45

In [45]:
np.sum(a2d, axis=0)

array([12, 15, 18])

In [46]:
np.sum(a2d, axis=1)

array([ 6, 15, 24])

In [47]:
np.mean(a2d, axis=0)

array([4., 5., 6.])

In [48]:
# exercise: prices and quantities

prices = np.array([3.99, 4.99, 3.99, 12.99])

quantities = np.array([3, 0, 0, 2])

# total cost?

# 3 * 3.99
# 0 * 4.99
# 0 * 3.99
# 2 * 12.99

np.sum(quantities * prices)

37.95

In [49]:
data = np.array([[3.99, 4.99, 3.99, 12.99], [3, 0, 0, 2]])
np.sum(data[0, :] * data[1, :])

37.95

In [51]:
masses = np.array([1.2, 2.2, 1.5, 2.0])
velocities = np.array([12.0, 14.0, 14.0, 7.5])

In [58]:
energies = masses * velocities ** 2 / 2
energies

array([ 86.4 , 215.6 , 147.  ,  56.25])

In [60]:
total_energy = np.sum(energies)
total_energy

505.25

In [64]:
x = np.arange(0, 2*np.pi, 0.01)
sin_x = np.sin(x)
cos_x = np.cos(x)

trig_values = np.array([x, sin_x, cos_x])
trig_values

array([[ 0.00000000e+00,  1.00000000e-02,  2.00000000e-02, ...,
         6.26000000e+00,  6.27000000e+00,  6.28000000e+00],
       [ 0.00000000e+00,  9.99983333e-03,  1.99986667e-02, ...,
        -2.31832300e-02, -1.31849251e-02, -3.18530179e-03],
       [ 1.00000000e+00,  9.99950000e-01,  9.99800007e-01, ...,
         9.99731233e-01,  9.99913075e-01,  9.99994927e-01]])

In [77]:
# verification:

np.square(sin_x) + np.square(cos_x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [79]:
# dice rolls:

# 1) 37
# 2) 31
# 3) 32

# simulate 1000000 x 10 dice rolls

dice_rolls = np.random.randint(1, 7, size=(1000000, 10))

In [82]:
# show first 3 rows
dice_rolls[0:3, :]

array([[6, 2, 4, 3, 3, 3, 4, 5, 2, 3],
       [6, 1, 2, 4, 1, 1, 2, 2, 3, 2],
       [1, 2, 4, 4, 6, 6, 5, 3, 3, 4]])

In [88]:
# with a for loop (not recommended)

results = []

for i in range(1000000):
    results.append(sum(dice_rolls[i, :]))

print(results[:10])

[35, 24, 38, 37, 44, 34, 35, 41, 32, 33]


In [92]:
# with numpy

dice_rolls.sum(axis=1)

array([35, 24, 38, ..., 32, 43, 34])

In [93]:
np.mean(dice_rolls.sum(axis=1))

34.994329

In [103]:
c = np.array([2.0, 4.0, 3.0, 1.0])

In [104]:
include = np.array([True, False, False, True])
c[include]

array([2., 1.])

In [105]:
include = c <= 2
c[include]

array([2., 1.])

In [100]:
c[c <= 2]

array([2, 1])

In [108]:
c_copy = c.copy()
c_copy[c_copy > 2] = np.nan
c_copy

array([ 2., nan, nan,  1.])