# NumPy

In [1]:
import numpy as np

In [2]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
# performance comparison

import time

input_data = range(0, 1000001)
squares = []

start = time.perf_counter()
for element in input_data:
    squares.append(element * element)
end = time.perf_counter()

print(end - start)


input_data_np = np.array(input_data, dtype="int64")

start = time.perf_counter()
squares_np = input_data_np * input_data_np
end = time.perf_counter()

print(end - start)


0.3355136999999786
0.004703099999915139


In [19]:
a2d.size

9

In [20]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
a2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
a2d.dtype

dtype('int32')

In [28]:
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.full((2, 6), 1.0)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
np.linspace(0, 1.0, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [31]:
np.arange(0, 3.14, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [56]:
rng = np.random.default_rng(seed=1)
print(rng.random((2, 2)))
print(rng.random((2, 2)))
print(rng.random((2, 2)))
print(rng.random((2, 2)))

r = rng.random((2, 2))
print(r)

r[1, 1]

[[0.51182162 0.9504637 ]
 [0.14415961 0.94864945]]
[[0.31183145 0.42332645]
 [0.82770259 0.40919914]]
[[0.54959369 0.02755911]
 [0.75351311 0.53814331]]
[[0.32973172 0.7884287 ]
 [0.30319483 0.45349789]]
[[0.1340417  0.40311299]
 [0.20345524 0.26231334]]


0.2623133404418495

## selecting elements

In [51]:
a1d[0]

9

In [48]:
a2d[0, 1]

2

In [49]:
a2d[0, :]

array([1, 2, 3])

In [54]:
a2d[:, 1]

array([2, 5, 8])

In [57]:
a1d[:3]

array([0, 1, 2])

In [58]:
a1d[3:6]

array([3, 4, 5])

In [59]:
a1d[6:]

array([6, 7, 8, 9])

In [60]:
a1d[0:8:2]

array([0, 2, 4, 6])

In [62]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])

In [63]:
a + b

array([2, 3, 4, 5])

In [64]:
a < b

array([ True,  True, False, False])

In [65]:
a == b

array([False, False,  True, False])

In [67]:
if np.array_equal(a, b):
    print("hello")

In [68]:
a + 1

array([1, 2, 3, 4])

In [71]:
a * a

array([0, 1, 4, 9])

In [73]:
a2d @ a2d

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [74]:
a2d * a2d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [75]:
a2d = np.array([[ "a", "b", "c"],
                [16, 25, 36],
                [49, 64, 81]])

In [76]:
headings = a2d[0, :]
headings

array(['a', 'b', 'c'], dtype='<U11')

In [77]:
data = a2d[1:, :]
data

array([['16', '25', '36'],
       ['49', '64', '81']], dtype='<U11')