In [1]:
import numpy as np

In [2]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a2d[0, 1]

2

In [8]:
a2d.mean(axis=0)

array([4., 5., 6.])

In [9]:
a = np.array([4.1, 2.7, -1, 3.8, -1])

In [10]:
a

array([ 4.1,  2.7, -1. ,  3.8, -1. ])

In [11]:
a_valid = a > 0

In [12]:
a_valid

array([ True,  True, False,  True, False])

In [13]:
a[a_valid]

array([4.1, 2.7, 3.8])

In [14]:
a[a > 0]

array([4.1, 2.7, 3.8])

In [15]:
a_invalid = a < 0
a_with_nans = np.copy(a)
a_with_nans[a_invalid] = np.nan

In [16]:
a_with_nans

array([4.1, 2.7, nan, 3.8, nan])

In [17]:
array = np.array([1, 2, 3])
array_view = array[:]
array_view[0] = 10 # DOES change array

In [18]:
array

array([10,  2,  3])