In [1]:
import numpy as np

In [2]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a1d * a1d

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
import math
import time

# measuring execution times

# compute square roots (with pure python) - from 0 to 1000000
# output: [0, 1, 1.41, 1.7.., ...., 1000]

original_list = list(range(0, 1000001))

# get the current (start) time
start_time = time.perf_counter()
root_list = []
for n in original_list:
    root = math.sqrt(n)
    root_list.append(root)
# get the current (end) time
end_time = time.perf_counter()
print(end_time - start_time)

# compute square roots (with numpy)

original_array = np.array(range(0, 1000001))

start_time = time.perf_counter()
root_array = np.sqrt(original_array)

end_time = time.perf_counter()
print(end_time - start_time)

0.3840906000000359
0.00449809999986428


In [27]:
a3d.shape

(2, 2, 2)

In [28]:
a3d.ndim

3

In [29]:
a3d.size

8

In [33]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
a2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
np.max(a2d)

9

In [38]:
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
np.arange(0, 3.14, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [40]:
np.linspace(0, 1.0, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [55]:
rng = np.random.default_rng(seed=1)
rng.random((2, 2))

array([[0.51182162, 0.9504637 ],
       [0.14415961, 0.94864945]])

In [56]:
rng.integers(1, 7, (2, 2))

array([[2, 2],
       [6, 3]], dtype=int64)

In [57]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# task: recreate a1d "automatically" (via arange or linspace)

np.arange(0, 10)

np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## selecting entries

In [61]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a2d[2, 1]

8

In [68]:
a2d[2, :]

array([7, 8, 9])

In [69]:
a2d[:, 0]

array([1, 4, 7])

## operators

In [72]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])

In [73]:
a + a

array([0, 2, 4, 6])

In [76]:
a < b

array([ True,  True, False, False])

In [78]:
a * 10

array([ 0, 10, 20, 30])

In [79]:
a + np.pi

array([3.14159265, 4.14159265, 5.14159265, 6.14159265])

In [80]:
a + np.e

array([2.71828183, 3.71828183, 4.71828183, 5.71828183])

In [81]:
np.nan

nan

In [82]:
x = np.array([3, 5, np.nan, 7])

In [83]:
x

array([ 3.,  5., nan,  7.])

In [84]:
x + a

array([ 3.,  6., nan, 10.])

In [85]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [87]:
np.round(np.sqrt(a))

array([0., 1., 1., 2.])

In [93]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.sum(a2d)

45

In [92]:
np.sum(a2d, axis=0)

array([12, 15, 18])

## Exercises

In [97]:
prices = np.array([3.99, 4.99, 3.99, 12.99])

quantities = np.array([3, 0, 0, 2])

# 3 * 3.99 + 2 * 12.99

# 37.95

np.sum(prices * quantities)

37.95

In [102]:
masses = np.array([1.2, 2.2, 1.5, 2.0])
velocities = np.array([12.0, 14.0, 14.0, 7.5])

energies = masses * velocities ** 2 / 2
print(energies)
print(np.sum(energies))

[ 86.4  215.6  147.    56.25]
505.25


In [104]:
x = np.arange(0, 2 * np.pi, 0.01)

sin_x = np.sin(x)
cos_x = np.cos(x)

trig = np.array([x, sin_x, cos_x])



In [ ]:
# [[4, 2, 3, 2, 1, 3, 7, 8, 8, 8],
#  [5, 3, 9, 1, 2, 3, 4, 6, 4, 2],
#  [],
#  ...
# ]

# [33, 37, 36, 40, 32, 32]

In [111]:
dice_rolls = np.random.randint(1, 7, size=(1000000, 10))

In [113]:
dice_rolls.shape

(1000000, 10)

In [115]:
# show the first row

dice_rolls[0, :]

array([4, 3, 6, 2, 5, 6, 6, 5, 4, 6])

In [120]:
# get the sum for each row
# [33, 37, 36, 40, 32, 32, ...]

results = np.sum(dice_rolls, axis=1)
results

array([47, 37, 40, ..., 38, 44, 39])

## boolean indexing

In [121]:
a = np.array([4.1, 2.7, -1, 3.8, -1])

In [122]:
a

array([ 4.1,  2.7, -1. ,  3.8, -1. ])

In [124]:
a_valid = a > 0

In [125]:
a_valid

array([ True,  True, False,  True, False])

In [128]:
a_filtered = a[a_valid]
a_filtered

array([4.1, 2.7, 3.8])

In [129]:
a_invalid = a < 0

In [130]:
a_invalid

array([False, False,  True, False,  True])

In [131]:
a_with_nans = np.copy(a)
a_with_nans[a_invalid] = np.nan

In [132]:
a_with_nans

array([4.1, 2.7, nan, 3.8, nan])

In [133]:
# long version

a_valid = a > 0
a_filtered = a[a_valid]

# short version

a_filtered = a[a > 0]

array([4.1, 2.7, 3.8])

In [136]:
# long version

a_invalid = a < 0
a_with_nans = np.copy(a)
a_with_nans[a_invalid] = np.nan

# short version

a_with_nans = np.copy(a)
a_with_nans[a < 0] = np.nan

array([4.1, 2.7, nan, 3.8, nan])

In [139]:
a_with_zeros = np.copy(a)
a_with_zeros[a < 0] = 0

a_with_zeros

array([4.1, 2.7, 0. , 3.8, 0. ])

In [141]:
np.where(a > 0, a, 0)

array([4.1, 2.7, 0. , 3.8, 0. ])