In [1]:
import time
time.sleep(3)
"hello"

'hello'

In [2]:
_ * 3

'hellohellohello'

In [3]:
_.upper()

'HELLOHELLOHELLO'

In [4]:
3

3

In [5]:
_ * 3

9

In [6]:
2 * 6

12

In [7]:
a=4

In [8]:
_

12

# Dokumentation mittels Markdown

## h2

- item 1
- item 2

In [9]:
import numpy as np

In [10]:
a2d = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
a2d

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [11]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
a3d[0][0][1]
a3d[0, 0, 1]

2

In [13]:
print(a3d.ndim)
print(a3d.shape)
print(a3d.size)

3
(2, 2, 2)
8


In [14]:
print(a2d[:, 0:1])

[[1]
 [2]
 [3]]


In [15]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(-a)
# np.array([-1, -2, -3])
print(a + b)
# np.array([3, 4, 5])
print(a * b)
# np.array([2, 4, 6])

[-1 -2 -3]
[3 4 5]
[2 4 6]


In [16]:
a3d + np.pi

array([[[ 4.14159265,  5.14159265],
        [ 6.14159265,  7.14159265]],

       [[ 8.14159265,  9.14159265],
        [10.14159265, 11.14159265]]])

In [17]:
#if a == b:
#    print("a and b equal")

In [18]:
np.array_equal

<function numpy.array_equal(a1, a2)>

In [19]:
import math

# Beispiel: Sinuswerte zu [0, 1, 2, 3, 4]

# mit und ohne NumPy

x = [1, 2, 3, 4]
x_a = np.array(x)

y = [math.sin(value) for value in x]
y_a = np.sin(x_a)

print(y)
print(y_a)

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [20]:
prices = np.array([3.99, 4.99, 3.99, 12.99])
# buying the first item 3 times and the last item 2 times
quantities = np.array([3, 0, 0, 2])

# solution: 37.95

print(np.sum(prices * quantities))

37.95


In [21]:
a = np.array([5, 1])
b = np.array([6, 8])
c = np.array([1, 3])

points = np.array([a, b, c])

points.mean(axis=0)



array([4., 4.])

In [22]:
a = np.array([5, 1])
b = np.array([6, 8])
c = np.array([1, 3])

s = (a + b + c) / 3
print(s)

points = np.array([
    [5, 1],
    [6, 8],
    [1, 3]
])

print(points.mean(axis=0))

[4. 4.]
[4. 4.]


In [23]:
x = np.arange(0, np.pi*2, 0.01)
sin = np.sin(x)
cos = np.cos(x)

result = np.array([x, sin, cos])
result

print(result[1]**2 + result[2]**2)
sums = np.sum(result[1:]**2, axis=0)
np.isclose(sums, 1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [24]:
x = np.arange(0, np.pi*2, 0.01)
s = np.sin(x)
c = np.cos(x)

t = np.array([x, s, c])
t

t[1]**2 + t[2]**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [25]:
len(dir(np))

621

In [26]:
sums.dtype

dtype('float64')

In [27]:
ints = np.array([1, 2, 3])
ints.dtype

dtype('int64')

In [28]:
# ints[0] = "test"

ValueError: invalid literal for int() with base 10: 'test'

In [29]:
ints.dtype

dtype('int64')

In [30]:
ints = ints.astype("float64")

In [31]:
import pandas as pd
euribor = pd.read_csv(
    "https://datahub.io/core/euribor/r/euribor-12m-monthly.csv"
)

In [33]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [39]:
array_3d.reshape(2, -1).T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
array_2d = np.array([[1, 2], [3, 4]])
array_3d = array_2d[:, :, np.newaxis]
array_3d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [44]:
list = [1, 2, 3]
list_copy = list
list_copy[0] = 10
print(list)

[10, 2, 3]


In [45]:
list = [1, 2, 3]
list_copy = list[:]
list_copy[0] = 10 # does NOT change list
print(list)

[1, 2, 3]


In [48]:
array = np.array([1, 2, 3])
array_view = array[1:]
array_view[0] = 10 # DOES change array
print(array)

[ 1 10  3]


In [57]:
np.concatenate([array_2d, array_2d], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [58]:
a = np.array([1, 1])

M = np.array([[0.707, 0.707],
              [-0.707, 0.707]])

print(a @ M)

[0.    1.414]


In [61]:
points = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

M = np.array([[0.707, 0.707],
              [-0.707, 0.707]])

print(points @ M)

[[ 0.     0.   ]
 [-0.707  0.707]
 [ 0.707  0.707]
 [ 0.     1.414]]


In [62]:
prices = np.array([3.99, 12.99, 5.90, 15])

quantities = np.array([[0, 80, 80, 100],
                       [100, 0, 0, 0],
                       [50, 0, 0, 50]])

prices @ quantities.T

array([3011.2,  399. ,  949.5])