In [4]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1, 1],
              [2, 3],
              [3, 2],
              [0, 0],
              [1, 1]])

y = np.array([4.58, 14.50, 11.98, 0.0, 4.80])

model = LinearRegression()
# lernen anhand der Eingangsdaten:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
yfit = model.predict([[1, 0], [0, 1], [2, 2]])
print(yfit)

[ 1.05276596  3.57276596 10.41148936]


In [12]:
print(model.intercept_)
print(model.coef_)

-0.38680851063829724
[1.43957447 3.95957447]


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

sample = ['problem of evil',
          'evil queen',
          'horizon problem']

vectorizer = CountVectorizer()
vectorizer.fit(sample)
print(vectorizer.vocabulary_)
X = vectorizer.transform(sample)
print(X)
print(X.todense())

{'problem': 3, 'of': 2, 'evil': 0, 'queen': 4, 'horizon': 1}
  (0, 0)	1
  (0, 2)	1
  (0, 3)	1
  (1, 0)	1
  (1, 4)	1
  (2, 1)	1
  (2, 3)	1
[[1 0 1 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]]
