In [1]:
import numpy as np

In [2]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

In [3]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# dice rolls

# 3, 2, 4, 1, 6, 6, 5, ... -> 37
# 4, 3, 6, 6, 1,           -> 40
#                             34
#                             35

simulation_10_dice = np.random.randint(1, 7, (10, ) )
sum_10_dice = np.sum(simulation_10_dice)
print(sum_10_dice)

simulation_1_million_times_10_dice = np.random.randint(1, 7, (1_000_000, 10))

simulation_1_million_times_10_dice[:5, :]

sums_1_million_times_10_dice = np.sum(simulation_1_million_times_10_dice, axis=1)
print(sums_1_million_times_10_dice)

38
[36 40 35 ... 29 26 41]


In [69]:
x = np.arange(0, 2*np.pi, 0.01)
sin_x = np.sin(x)
cos_x = np.cos(x)

values = np.array([x, sin_x, cos_x])
values = np.concatenate([x.reshape(1, -1), sin_x.reshape(1, -1), cos_x.reshape(1, -1)], axis=0)

values[:, :5]

array([[0.        , 0.01      , 0.02      , 0.03      , 0.04      ],
       [0.        , 0.00999983, 0.01999867, 0.0299955 , 0.03998933],
       [1.        , 0.99995   , 0.99980001, 0.99955003, 0.99920011]])

In [42]:
a = np.array([4.1, 2.7, -1, 3.8, -1])

a_valid = a > 0
a[a_valid]

a_filtered = a[a > 0]
print(a_filtered)

a_with_nans = a.copy()
a_with_nans[a_with_nans < 0] = np.nan
print(a_with_nans)

[4.1 2.7 3.8]
[4.1 2.7 nan 3.8 nan]


In [47]:
a2d

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [49]:
a2d.reshape(9)

array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [51]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
points = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])

m = np.array([[0.707, 0.707],
              [-0.707, 0.707]])

print(points @ m @ m)

[[ 0.00000000e+00  0.00000000e+00]
 [-9.99698000e-01  1.37436729e-17]
 [-9.99698000e-01  9.99698000e-01]
 [-1.37436729e-17  9.99698000e-01]]


In [73]:
prices = np.array([3.99, 12.99, 5.90, 15])
quantities = np.array([[0, 80, 80, 100],
                       [100, 0, 0, 0],
                       [50, 0, 0, 50]])

prices @ quantities.T

array([3011.2,  399. ,  949.5])