In [1]:
import pandas as pd

In [2]:
# load data via pandas
iris = pd.read_csv(
    "http://archive.ics.uci.edu/ml/" +
    "machine-learning-databases/iris/iris.data",
    header=None,
    names=["sepal_length", "sepal_width", "petal_length",
           "petal_width", "species"]
)

In [3]:
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
iris_shuffled = iris.sample(frac=1.0)
iris_shuffled

sepal_length  sepal_width  petal_length  petal_width          species
131           7.9          3.8           6.4          2.0   Iris-virginica
106           4.9          2.5           4.5          1.7   Iris-virginica
51            6.4          3.2           4.5          1.5  Iris-versicolor
29            4.7          3.2           1.6          0.2      Iris-setosa
62            6.0          2.2           4.0          1.0  Iris-versicolor
..            ...          ...           ...          ...              ...
138           6.0          3.0           4.8          1.8   Iris-virginica
64            5.6          2.9           3.6          1.3  Iris-versicolor
120           6.9          3.2           5.7          2.3   Iris-virginica
33            5.5          4.2           1.4          0.2      Iris-setosa
83            6.0          2.7           5.1          1.6  Iris-versicolor

[150 rows x 5 columns]

In [5]:
measurements = iris_shuffled[[
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
]].to_numpy()

In [6]:
species = (
    iris_shuffled["species"]
    .replace({
        "Iris-setosa": 0,
        "Iris-versicolor": 1,
        "Iris-virginica": 2,
    })
    .to_numpy()
)

In [7]:
species

array([2, 2, 1, 0, 1, 2, 2, 0, 2, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2,
       0, 2, 0, 1, 2, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 0, 2, 1,
       0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1,
       1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 2, 2, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 0, 2, 0,
       2, 0, 1, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       0, 0, 1, 1, 2, 1, 2, 0, 1, 1, 1, 1, 0, 2, 1, 2, 0, 1])

In [8]:
x = measurements

In [9]:
y = species

In [10]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

In [11]:
model.fit(x[:130], y[:130])

KNeighborsClassifier()

In [12]:
import numpy as np
demo_measurements = np.array([
    [5.3, 3.4, 1.9, 0.6],
    [6.0, 3.0, 4.7, 1.5],
    [6.5, 3.1, 5.0, 1.7]
])

In [13]:
model.predict(demo_measurements)

array([0, 1, 1])

In [14]:
model.predict_proba(demo_measurements)

array([[1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 0.6, 0.4]])

In [15]:
measurements_val = measurements[130:]
species_val = species[130:]

In [16]:
model.score(measurements_val, species_val)

0.95