In [1]:
import numpy as np

In [2]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
a2d + a2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a3d.shape

(2, 2, 2)

In [11]:
a2d.shape

(3, 3)

In [13]:
a3d.size

8

In [16]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
a2d.dtype

dtype('int64')

In [19]:
np.full((2, 6), 1.0)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0, 1.0, 101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [22]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a2d[0, 1]

2

In [24]:
a2d[0, :]

array([1, 2, 3])

In [25]:
a2d[:, 1]

array([2, 5, 8])

In [26]:
a1d[:3]

array([0, 1, 2])

In [27]:
a1d[3:6]

array([3, 4, 5])

In [28]:
a1d[6:]

array([6, 7, 8, 9])

In [29]:
a1d[0:8:2]

array([0, 2, 4, 6])

In [30]:
names = ["Alice", "Bob", "Charlie"]

In [33]:
names[0::2]

['Alice', 'Charlie']

In [34]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])

In [35]:
a < b

array([ True,  True, False, False])

In [36]:
a + b

array([2, 3, 4, 5])

In [37]:
a + 1

array([1, 2, 3, 4])

In [38]:
np.nan + 1

nan

In [42]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [44]:
np.sum(a2d)

45

In [47]:
np.sum(a2d, axis=1)

array([ 6, 15, 24])

In [48]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
prices = np.array([3.99, 4.99, 3.99, 12.99])
# buying the first item 3 times and the last item 2 times
quantities = np.array([3, 0, 0, 2])

In [53]:
total_price_per_product = prices * quantities
total_price_per_product

array([11.97,  0.  ,  0.  , 25.98])

In [54]:
np.sum(total_price_per_product)

37.95

In [55]:
def sumx(a, b):
    return np.sum(a * b)

In [56]:
sumx(prices, quantities)

37.95

In [57]:
a = np.array([4.1, 2.7, -1, 3.8, -1])


In [62]:
a_valid = a > 0
a[a_valid]

array([4.1, 2.7, 3.8])

In [63]:
a[a > 0]

array([4.1, 2.7, 3.8])