In [ ]:
import numpy as np

In [ ]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]], dtype="uint8")

In [ ]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=uint8)

In [ ]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a3d.dtype

dtype('uint8')

In [ ]:
date = (2022, 2, 7)

In [ ]:
dates = [(2022, 2, 7), (2002, 2, 1)]

In [ ]:
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
for i in range(2, 10, 2):
    print(i)

2
4
6
8


In [ ]:
np.arange(0, 3.14, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [ ]:
np.linspace(0, 1.0, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
rng = np.random.default_rng(seed=2)

print(rng.random((2, 2)))
print(rng.random((2, 2)))

[[0.26161213 0.29849114]
 [0.81422574 0.09191594]]
[[0.60010053 0.72856053]
 [0.18790107 0.05514663]]


In [ ]:
rng.integers(1, 7, (2, 2))

array([[2, 4],
       [2, 1]])

In [ ]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=uint8)

In [ ]:
np.array([1]) / np.array([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

In [ ]:
np.sum(a2d)

45

In [ ]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a2d, axis=0)

array([12, 15, 18])

In [ ]:
np.sum(a2d, axis=1)

array([ 6, 15, 24])

In [ ]:
x = 4

In [ ]:
2 < x and x < 10

True

In [ ]:
2 < x < 10

True

In [ ]:
(2 < x) & (x < 10)

In [ ]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
row1 = np.copy(a2d[1, :])

In [ ]:
row1

array([4, 5, 6])

In [ ]:
row1[0] = 40

In [ ]:
row1

array([40,  5,  6])

In [ ]:
a2d

array([[ 1,  2,  3],
       [40,  5,  6],
       [ 7,  8,  9]])