In [3]:
import numpy as np

a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
import time

a = range(0, 1_000_001)

start_a = time.perf_counter()
squares_a = [element**2 for element in a]
end_a = time.perf_counter()

b = np.arange(0, 1_000_001)

start_b = time.perf_counter()
squares_b = b**2
end_b = time.perf_counter()

print(end_a - start_a)
print(end_b - start_b)


4.057948199999373
0.03958280000006198


In [6]:
squares

array([         0,          1,          4, ..., -731379964, -729379967,
       -727379968], dtype=int32)

In [8]:
a3d.shape

(2, 2, 2)

In [9]:
a3d.ndim

3

In [10]:
a3d.size

8

In [12]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
a2d.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [15]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1d[0] = np.inf

OverflowError: cannot convert float infinity to integer

In [25]:
a1d_float = a1d.astype("float")

In [26]:
a1d_float

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
np.array([2.71828, 0.271828], dtype="float16")

array([2.719 , 0.2717], dtype=float16)

In [28]:
np.array([65450, 65500, 65550], dtype="float16")

array([65440., 65500.,    inf], dtype=float16)

In [29]:
np.array(
    [3.141e-5, 3.141e-6, 3.141e-7, 3.141e-8, 3.141e-9],
    dtype="float16"
)

array([3.14e-05, 3.16e-06, 2.98e-07, 5.96e-08, 0.00e+00], dtype=float16)

In [41]:
rng = np.random.default_rng(seed=1)
rng.random((2, 2))

array([[0.51182162, 0.9504637 ],
       [0.14415961, 0.94864945]])

In [44]:
a1d[0]

0

In [46]:
a2d[0, :]

array([1, 2, 3])

In [47]:
a2d[:, 0]

array([1, 4, 7])

In [48]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a2d[1, 2]

6

In [54]:
a1d[0:8:2]

array([0, 2, 4, 6])

In [55]:
a1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
if np.array_equal(a1d, np.arange(0, 10)):
    print("equal")

equal


In [57]:
a1d == np.arange(0, 10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [59]:
np.pi

3.141592653589793

In [60]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743, ..., -0.70613761,
       -0.97735203, -0.3499935 ])

In [62]:
np.sum(a2d, axis=0)

array([12, 15, 18])

In [63]:
np.sum(a2d, axis=1)

array([ 6, 15, 24])

In [71]:
# x, sin(x), cos(x)

x = np.arange(0, 3.14, 0.01)

sin_x = np.sin(x)
cos_x = np.cos(x)

values = np.array([x, sin_x, cos_x])

values[:, :5]

array([[0.        , 0.01      , 0.02      , 0.03      , 0.04      ],
       [0.        , 0.00999983, 0.01999867, 0.0299955 , 0.03998933],
       [1.        , 0.99995   , 0.99980001, 0.99955003, 0.99920011]])

In [74]:
values[1, :]**2 + values[2, :]**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.