In [2]:
import time
time.sleep(3)
"hello"

'hello'

In [3]:
a = 3

In [4]:
a

3

In [5]:
a += 1

# heading

- list item 1
- list item 2

In [6]:
import numpy as np

In [11]:
!dir

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 76CD-8EAB

 Verzeichnis von c:\Users\marko\repos\courses-code\2021-03-15-python-data-science

15.03.2021  07:40    <DIR>          .
15.03.2021  07:40    <DIR>          ..
17.02.2021  10:50    <DIR>          tag1
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 142.055.813.120 Bytes frei


In [12]:
a1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

In [15]:
a1d * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
np.linspace(0, 1.0, 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [19]:
np.arange(0, 3.14, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [33]:
rng = np.random.default_rng(seed=2)

a = rng.random((2, 2))
b = rng.integers(1, 7, (2, 2))
print(a)
print(b)

[[0.26161213 0.29849114]
 [0.81422574 0.09191594]]
[[3 4]
 [5 5]]


In [35]:
np.random.random((3, 2))

array([[0.63424634, 0.00975324],
       [0.40055674, 0.73250431],
       [0.06648289, 0.78268527]])