In [1]:
import numpy as np

In [9]:
a = np.array([1, 2, 3], dtype="float32")

print(a[0])
print(type(a))
print(a.dtype)

1.0
<class 'numpy.ndarray'>
float32


In [14]:
c = np.array( [ [1, 2, 3], [11, 12, 13] ] )
print(c + c)
print(c + 1)

[[ 2  4  6]
 [22 24 26]]
[[ 2  3  4]
 [12 13 14]]


In [10]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(a + b)
# np.array([3, 4, 5])
print(a * b)
# np.array([2, 4, 6])

[3 4 5]
[2 4 6]


# total price

given prices and quantities, determine a total price

In [17]:
prices = np.array([3.99, 4.99, 3.99, 12.99])
# buying the first item 3 times and the last item 2 times
quantities = np.array([3, 0, 0, 2])

print(prices * quantities)
print(np.sum(prices * quantities))

[11.97  0.    0.   25.98]
37.95


# centroid

In [18]:
a = np.array([5, 1])
b = np.array([6, 8])
c = np.array([1, 3])

centroid = (a + b + c) / 3
print(centroid)

[4. 4.]
